const colorsOld = {
  white: '#FFFFFF',
  offwhite: '#F6F7FB',
  blueGray: '#DEE4F1',
  green: '#63BA67',
  lightestGray: '#AEB4C4',
  lightGray: '#D3D6DD',
  gray: '#B1B6C1',
  darkGray: '#89878B',
  blue: '#45ADF2',
  lightBlack: '#2F3A3D',
  red: '#E7615B',
};

const colors = {
  messageBackgroundLightUser: '#45ADF2',
  messageBackgroundLight: '#FFFFFF',
  messageLight: '#FFFFFF',
  messageLightUser: '#FFFFFF',
  messageTitleUser: '#2F3A3D',
  messageTitle: '#010101',
  messageInputBackground: '#FFFFFF',
  messageContentUser: '#89878B',
  messageContent: '#010101',
  messageTimestampUser: '#afdfff',
  messageTimestamp: '#b7b7b7',
  offwhite: '#F6F7FB',
  blueGray: '#DEE4F1',
  sideBackground: '#63BA67',
  sideBackgroundAccent: '#a3e4a6',
  green: '#63BA67',
  lightestGray: '#AEB4C4',
  lightGray: '#D3D6DD',
  inputColor: '#2b2b2b',
  darkGray: '#89878B',
  lightBlack: '#2F3A3D',
  red: '#E7615B',
  white: '#FEFEFE',
  lightRed: '#EF615B',
};

export { colors };
